baseURL = 'https://hea.care/'
languageCode = 'en-us'
title = 'Happily Ever After'

[markup.goldmark.renderer]
  unsafe = true

[params]
  openGraph = true
  description = 'TODO'
  images = ['site-feature-image.jpg']
  title = 'Happily Ever After'
[params.style]
  container = 'px-8 mx-auto max-w-3xl'
  containerSmall = 'px-16 mx-auto max-w-xl'
  button = 'px-4 py-2 rounded-lg bg-rose-500 border-2 border-transparent hover:bg-rose-600 outline-none ring-offset-2 focus-visible:ring-rose-600 focus-visible:ring-2 text-white font-semibold'
  inputText = 'px-4 py-2 rounded-lg bg-neutral-200 border-2 border-transparent focus:border-rose-500 focus:ring-0'
[params.navbar]
  logo = 'images/logo.png'
